; FONTS
GUICtrlSetFont($pathFFButton, 10, 800, 0, "Segoe UI")
GUICtrlSetFont($pathFFDesc, 9, 800, 0, "Segoe UI")
GUICtrlSetFont($pathFFTF, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($pathTSButton, 10, 800, 0, "Segoe UI")
GUICtrlSetFont($pathTSDesc, 9, 800, 0, "Segoe UI")
GUICtrlSetFont($pathTSTF, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($hideEncodingCheck, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($defaultsDesc, 9, 800, 0, "Segoe UI")
GUICtrlSetFont($newLooperDefaultCheck, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($recycleDefaultCheck, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($defaultHandlesList, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($defaultHandlesDesc, 8, 800, 0, "Segoe UI")
GUICtrlSetFont($defaultTrimList, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($defaultTrimDesc, 8, 800, 0, "Segoe UI")
GUICtrlSetFont($cancelButton, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($saveButton, 9, 800, 0, "Segoe UI")

; VALUES FOR COMBO BOXES
GUICtrlSetData($defaultHandlesList, "1 second|2 seconds|3 seconds|4 seconds|5 seconds")
GUICtrlSetData($defaultTrimList, "Trim Losslessly (ffmpeg)|Transcode to ProRes")