; FONTS FOR THE INTRO WINDOW
GUICtrlSetFont($_WT1, 10, 800, 0, "Segoe UI")
GUICtrlSetFont($_WT2, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($_WT3, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($_WT4, 9, 400, 0, "Segoe UI")
GUICtrlSetFont($_WT5, 9, 400, 0, "Segoe UI")

GUICtrlSetFont($_FFMPEGURL, 9, 800, 0, "Segoe UI")

GUICtrlSetFont($IntroPathFFTF, 8, 400, 0, "Segoe UI")
GUICtrlSetFont($IntroPathFFButton, 9, 400, 0, "Segoe UI")

GUICtrlSetFont($IntroCancelButton, 10, 400, 0, "Segoe UI")
GUICtrlSetFont($IntroOKButton, 10, 400, 0, "Segoe UI")

; TEXT FOR THE INTRO WINDOW
GUICtrlSetData($_WT2, StringFormat("Looper Trimmer is an EDL-like editing\r\nprogram for .looper files generated by\r\nMPC-HC Looper."))
GUICtrlSetData($_WT3, StringFormat("To use Looper Trimmer, the program\r\nneeds to know the path to ffmpeg,\r\nwhich is the primary tool Looper \r\nTrimmer uses to trim .looper file events.  \r\nIf you don"&Chr(39)&"t have ffmpeg installed, you\r\ncan download the static version here -"))
GUICtrlSetData($_WT4, StringFormat("If you already have ffmpeg installed\r\n(or you have just installed it), tell\r\nLooper Trimmer where the ffmpeg.exe\r\nfile is here, by clicking on the "&Chr(34)&"..."&Chr(34)&" button"))
GUICtrlSetData($_WT5, StringFormat("Once you have that set up, you can use\r\nLooper Trimmer to take a list of events\r\nset up in a .looper file, and trim them to\r\nshorter versions of the original file,\r\nsaving space and condensing the .looper\r\nfile to only the parts necessary to loop\r\nthe events in the file."))